public class OpportunityDTO {
    public double amount {get; set;}
    public String description {get; set;}
    public String forecastcategoryname {get; set;}
    public String leadsource {get; set;}
    public String name {get; set;}
    public String nextstep {get; set;}
    public Integer probabliity {get; set;}
    public double quote {get; set;}
    public String stagename {get; set;}
    public String type {get; set;}
}